# Generated by Django 5.0.7 on 2024-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_exam_given_exam_date_alter_exam_last_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='complete_exam',
            field=models.BooleanField(default=False),
        ),
    ]
