# Generated by Django 5.1.1 on 2024-09-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_to_generate',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExamDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty1_percentage', models.IntegerField(default=0)),
                ('difficulty2_percentage', models.IntegerField(default=0)),
                ('difficulty3_percentage', models.IntegerField(default=0)),
                ('difficulty4_percentage', models.IntegerField(default=0)),
                ('difficulty5_percentage', models.IntegerField(default=0)),
                ('difficulty6_percentage', models.IntegerField(default=0)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='quiz.exam')),
            ],
            options={
                'verbose_name': 'Exam Difficulty',
                'verbose_name_plural': 'Exam Difficulties',
            },
        ),
    ]
