# Generated by Django 5.0.7 on 2024-07-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_exam_complete_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='complete_exam',
        ),
    ]
