# Generated by Django 5.1.1 on 2024-09-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
