# Generated by Django 5.1.1 on 2024-09-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_status_description_question_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit for this question in seconds'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.exam'),
        ),
        migrations.AlterField(
            model_name='status',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='quiz.exam'),
        ),
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='quiz.question')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
