# Generated by Django 5.1.1 on 2024-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_questionstatus_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstatus',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
