# Generated by Django 5.1.1 on 2024-09-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_questionstatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionstatus',
            old_name='reviewer',
            new_name='updated_by',
        ),
    ]
