# Generated by Django 5.1.1 on 2024-09-15 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_rename_updated_by_questionstatus_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstatus',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='questionstatus',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='questionstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
