# Generated by Django 5.1.1 on 2024-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='submitted', max_length=30, null=True),
        ),
    ]
