# Generated by Django 5.1.1 on 2024-09-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_question_updated_at_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
